name: Snapshot from Gitea
on: workflow_dispatch

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone --depth=1 https://gitea.com/easy3dfun/lensholder.git
          rm -r lensholder/.git
          git add -A
          git commit -m "Snapshot $(date)"
          git push
