name: Snapshot from Gitea
on: workflow_dispatch

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rm -rf lensholder
          git clone --depth=1 https://gitea.com/easy3dfun/lensholder.git
          rm -r lensholder/.git
          rm -rf print_objects
          git clone --depth=1 https://gitea.com/easy3dfun/print_objects.git
          rm -r print_objects/.git
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Snapshot $(date)"
          git push
